name: conda build

on: [ push ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Set paths and variables windows
        if: startsWith(matrix.os, 'windows')
        run: |
          echo "$env:CONDA\condabin" | Out-File -FilePath $env:GITHUB_PATH -Append
          echo "$env:CONDA\Library\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
          echo "PROJ_DATA=$env:CONDA\Library\share\proj" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Set paths and variables
        if: ${{ ! startsWith(matrix.os, 'windows') }}
        run: |
          echo "$CONDA/bin" >> $GITHUB_PATH
          echo "PROJ_DATA=$CONDA/share/proj" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          conda env update --file environment.yml --name base
      - name: Lint with flake8
        run: |
          conda install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Install package
        run: |
          pip install .
      - name: Test with pytest
        run: |
          conda install pytest coverage
          coverage run -m pytest
      - name: Publish to coveralls.io
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ github.token }}
