name: conda build

on: [ "push" ]

jobs:
  linux:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: '3.10'
          environment-file: environment.yml
      - name: Lint with flake8
        shell: bash -el {0}
        run: |
          conda install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Install package
        shell: bash -el {0}
        run: |
          pip install .
      - name: Test with pytest
        shell: bash -el {0}
        run: |
          conda install pytest coverage
          coverage run -m pytest
          coverage xml
      - name: Publish to coveralls.io
        uses: coverallsapp/github-action@v2.3.0
        with:
          path-to-lcov: coverage.xml
          github-token: ${{ secrets.GITHUB_TOKEN }}
